cabal-version:      3.0
name:               bombbusters

-- The package version.
-- See the Haskell package versioning policy (PVP) for standards
-- guiding when and how versions should be incremented.
-- https://pvp.haskell.org
-- PVP summary:     +-+------- breaking API changes
--                  | | +----- non-breaking API additions
--                  | | | +--- code changes with no API change
version:            0.2.0.0

license:            BSD-3-Clause
license-file:       LICENSE

-- base version (0.1.0.0) is from Joshua Rebay
author:             Joshua Rebay, Mona Winklmann  
maintainer:         mona.win.25.9@gmail.com
copyright:          Copyright (c) 2025, Joshua Rebay
category:           Game, Web
build-type:         Simple
extra-doc-files:    CHANGELOG.md, README.md

common warnings
    ghc-options: -Wall

library
    import:           warnings
    hs-source-dirs:   src
    exposed-modules:
        Config
        InitGame
        Types
        GameLoop
        GameLogic.Actions
        GameLogic.Core
        GameLogic.Display
        GameLogic.Input
        GameLogic.Util
        GameLogic.Equipment
        BotLogic.Interface
        BotLogic.BotTypes
        BotLogic.Strategies
        BotLogic.KnowledgeBase
        BotLogic.ConstraintSolver
        BotLogic.Inference
        BenchmarkLog
    build-depends:
        base ^>=4.20.0.0,
        mtl,
        random,
        random-shuffle,
        containers,
        pretty-simple,
        sbv,
        ansi-terminal,
        aeson,
        bytestring,
        time,
        directory,
        filepath
    default-language: Haskell2010

executable bombbusters
    import:           warnings
    main-is:          Main.hs
    hs-source-dirs:   app
    build-depends:
        base,
        bombbusters,
        hspec,
        random,
        random-shuffle,
        containers,
        pretty-simple,
        mtl,
        scotty,
        text,
        wai,
        http-types,
        wai-middleware-static,
        warp,
        stm
    ghc-options:      -threaded
    default-language: Haskell2010

